const Menu=[
    {
        id:1,
        image:"https://i.pinimg.com/originals/71/d6/db/71d6db959ed3f8e47e7ef8ccbf74ea7f.jpg",
        name:"Maggi",
        category: "breakfast",
        price:"99₹",
    },
    {
        id:2,
        image:"https://images.unsplash.com/photo-1539252554453-80ab65ce3586?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2FuZHdpY2h8ZW58MHx8MHx8fDA%3D&w=1000&q=80",
        name:"Sandwich",
        category: "breakfast",
        price:"119₹",
    },
    {
        id:3,
        image:"https://wallpapercave.com/wp/wp2691065.jpg",
        name:"Hot Dog",
        category: "evening",
        price:"149₹",
    },
    {
        id:4,
        image:"https://images.pexels.com/photos/3926123/pexels-photo-3926123.jpeg?cs=srgb&dl=pexels-bishop-tamrakar-3926123.jpg&fm=jpg",
        name:"Momo",
        category: "evening",
        price:"99₹",
    },
    {
        id:5,
        image:"https://images.pexels.com/photos/4001867/pexels-photo-4001867.jpeg?cs=srgb&dl=pexels-dima-valkov-4001867.jpg&fm=jpg",
        name:"Spring Roll",
        category: "evening",
        price:"139₹",
    },
    {
        id:6,
        image:"https://images3.alphacoders.com/131/1313839.jpg",
        name:"Burger",
        category: "evening",
        price:"105₹",
    },
    {
        id:7,
        image:"https://wallpapercave.com/wp/wp7485021.jpg",
        name:"Aloo Paratha",
        category: "breakfast",
        price:"99₹",
    },
    {
        id:8,
        image:"https://www.funfoodfrolic.com/wp-content/uploads/2018/08/8.jpg",
        name:"Dal Tadka, Bhindi Sabzi, Rajma Masala, Soya Chaap Tikka Masala, Mango Pickle, Chapati, Rice.",
        category: "lunch",
        price:"199₹",
    },
    {
        id:9,
        image:"https://www.funfoodfrolic.com/wp-content/uploads/2018/08/5.jpg",
        name:"Dhaba Dal Tadka, Paneer Butter Masala, Karela Sabzi, Boondi Raita, Chutney, Salad, Paratha",
        category: "lunch",
        price:"239₹",
    },
    {
        id:10,
        image:"https://www.funfoodfrolic.com/wp-content/uploads/2018/08/10.jpg",
        name:"Chana Curry, Dal Fry, Aloo Gutke, Tandoori Paratha, Rice, Salad, Achaar, Masala Chaas, Mango. ",
        category: "dinner",
        price:"290₹",
    },
    {
        id:11,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuJHYQCymUC_CwBjZZrD98kDw5wn6Bq950_2HYlHs0_w&s",
        name:"Panner Tikka",
        category: "dinner",
        price:"299₹",
    },
   
    {
        id:12,
        image:"https://img-global.cpcdn.com/recipes/3b9c6d673a81d0e8/1200x630cq70/photo.jpg",
        name:"Chinese Bhel , eCurry",
        category: "dinner",
        price:"99₹",
    },
    {
        id:13,
        image:"https://www.nehascookbook.com/wp-content/uploads/2022/09/Punjabi-thali-WS-696x392.jpg",
        name:"Punjabi thali",
        category: "lunch",
        price:"399₹",
    },
    {
        id:14,
        image:"https://c8.alamy.com/comp/EYER6H/indian-gulab-jamun-sweet-dessert-EYER6H.jpg",
        name:"Gujab Jamun",
        category: "Desert",
        price:"89₹",
    },
    {
        id:15,
        image:"https://i.pinimg.com/originals/f0/16/2a/f0162a5dc26829f91398021606f72c05.jpg",
        name:"Cake",
        category: "Desert",
        price:"99₹",
    },
    
    {
        id:"39",
        image:"https://upload.wikimedia.org/wikipedia/commons/5/58/Samosa_dish.jpg",
        Name:"Samosa",
        category:"evening",
        price:"99₹",
    },

]
export default Menu;